<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-03T00:04:05 IST" name="Suite" finished-at="2023-10-03T00:04:44 IST" duration-ms="38821">
    <groups>
    </groups>
    <test started-at="2023-10-03T00:04:05 IST" name="Test" finished-at="2023-10-03T00:04:44 IST" duration-ms="38821">
      <class name="com.banking.testcases.TC_LoginDDT_002">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.banking.testcases.TC_LoginDDT_002@8458f04]" started-at="2023-10-03T00:04:05 IST" name="setup" finished-at="2023-10-03T00:04:10 IST" duration-ms="4479" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginddt(java.lang.String,java.lang.String)[pri:0, instance:com.banking.testcases.TC_LoginDDT_002@8458f04]" started-at="2023-10-03T00:04:11 IST" name="loginddt" data-provider="TestData" finished-at="2023-10-03T00:04:21 IST" duration-ms="9727" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr530490]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[begEpUs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginddt -->
        <test-method signature="loginddt(java.lang.String,java.lang.String)[pri:0, instance:com.banking.testcases.TC_LoginDDT_002@8458f04]" started-at="2023-10-03T00:04:21 IST" name="loginddt" data-provider="TestData" finished-at="2023-10-03T00:04:25 IST" duration-ms="4249" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr530491]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[begEpUs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.banking.testcases.TC_LoginDDT_002.loginddt(TC_LoginDDT_002.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginddt -->
        <test-method signature="loginddt(java.lang.String,java.lang.String)[pri:0, instance:com.banking.testcases.TC_LoginDDT_002@8458f04]" started-at="2023-10-03T00:04:25 IST" name="loginddt" data-provider="TestData" finished-at="2023-10-03T00:04:32 IST" duration-ms="7062" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr530490]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[begEpUs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginddt -->
        <test-method signature="loginddt(java.lang.String,java.lang.String)[pri:0, instance:com.banking.testcases.TC_LoginDDT_002@8458f04]" started-at="2023-10-03T00:04:32 IST" name="loginddt" data-provider="TestData" finished-at="2023-10-03T00:04:37 IST" duration-ms="4836" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr530492]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[begEpUs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.banking.testcases.TC_LoginDDT_002.loginddt(TC_LoginDDT_002.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginddt -->
        <test-method signature="loginddt(java.lang.String,java.lang.String)[pri:0, instance:com.banking.testcases.TC_LoginDDT_002@8458f04]" started-at="2023-10-03T00:04:37 IST" name="loginddt" data-provider="TestData" finished-at="2023-10-03T00:04:44 IST" duration-ms="6661" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr530490]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[begEpUs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginddt -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.banking.testcases.TC_LoginDDT_002@8458f04]" started-at="2023-10-03T00:04:44 IST" name="tearDown" finished-at="2023-10-03T00:04:44 IST" duration-ms="381" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.banking.testcases.TC_LoginDDT_002 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
